version: "3.3"

networks:
    # Allow the use of traefik in other docker-compose.yml files
    reseau_lakaza:
        external: true

services:

  traefik:
    image: "traefik:v2.0"
    restart: always
    container_name: "traefik"
    command:
      # Only for development environment
      #- "--log.level=DEBUG"
      # - "--api.insecure=true"
      #tableau de bord
      - "--api.dashboard=true"
      # Get Docker as the provider
      - "--providers.docker=true"
      # Avoid that all containers are exposed
      - "--providers.docker.exposedbydefault=false"
      # Settle the ports for the entry points
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web-secure.address=:443"

      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      - "--certificatesresolvers.mytlschallenge.acme.email=contact@gdna.re"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/conf/acme.json"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefikAdmin.gdna.eu`)"
      #sécurise traefik
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=admin:$apr1$3OsOk3wZ$UnNNrx4Z.1nabPRDLI.cY."
      - "traefik.http.routers.api.entrypoints=web-secure"
      - "traefik.http.routers.api.tls.certresolver=mytlschallenge"

      # middleware redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # global redirect to https
      - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirs.entrypoints=web"
      - "traefik.http.routers.redirs.middlewares=redirect-to-https"


    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - "traefik-net"
    volumes:
      # Store certificates in ./letsencrypt/acme.json
      - "./conf:/conf"
      # Connect to Doker socket
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
